"""Add columns

Revision ID: 0c5ad77f3d53
Revises: 
Create Date: 2025-11-21 09:24:03.755015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5ad77f3d53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_appointments_code'))
        batch_op.drop_index(batch_op.f('idx_appointments_date'))
        batch_op.drop_index(batch_op.f('idx_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('idx_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('idx_appointments_status'))

    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('doctor_schedules_doctor_id_day_of_week_start_time_key'), type_='unique')
        batch_op.create_unique_constraint('unique_schedule_slot', ['doctor_id', 'day_of_week', 'start_time'])

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_doctors_available'))
        batch_op.drop_index(batch_op.f('idx_doctors_department_id'))
        batch_op.drop_index(batch_op.f('idx_doctors_user_id'))

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_medical_records_doctor_id'))
        batch_op.drop_index(batch_op.f('idx_medical_records_patient_id'))
        batch_op.drop_index(batch_op.f('idx_medical_records_visit_date'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_role', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('idx_notifications_is_read'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_appointment_id'))
        batch_op.drop_index(batch_op.f('idx_payments_patient_id'))
        batch_op.drop_index(batch_op.f('idx_payments_status'))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reviews_doctor_id'))
        batch_op.drop_index(batch_op.f('idx_reviews_patient_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_phone'))
        batch_op.drop_index(batch_op.f('idx_users_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_reviews_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_reviews_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_appointment_id'), ['appointment_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_is_read'), ['is_read'], unique=False)
        batch_op.drop_column('target_role')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_medical_records_visit_date'), ['visit_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_medical_records_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_medical_records_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_doctors_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_doctors_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_doctors_available'), ['is_available'], unique=False)

    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.drop_constraint('unique_schedule_slot', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('doctor_schedules_doctor_id_day_of_week_start_time_key'), ['doctor_id', 'day_of_week', 'start_time'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_appointments_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_appointments_code'), ['appointment_code'], unique=False)

    # ### end Alembic commands ###
