"""Add sender_id to notifications

Revision ID: 926062b98eab
Revises: 0c5ad77f3d53
Create Date: 2025-11-21 09:35:00.131652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926062b98eab'
down_revision = '0c5ad77f3d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
